---
- name: Deploy Foundation Lab
  hosts: all
  gather_facts: false
  tasks:
    - name: 1. Configure Underlay
      cisco.iosxr.iosxr_config:
        src: "../templates/underlay.j2"

    - name: 2. Configure BGP Control Plane
      cisco.iosxr.iosxr_config:
        src: "../templates/bgp_evpn.j2"

    - name: 3. Configure Telemetry
      cisco.iosxr.iosxr_config:
        src: "../templates/telemetry.j2"
      when: role == 'PE'